transcription_lang = {
    "Japanese Japan":"ja-JP",
    "English United States":"en-US",
    "English United Kingdom":"en-GB",
    "Afrikaans South Africa":"af-ZA",
    "Arabic Algeria":"ar-DZ",
    "Arabic Bahrain":"ar-BH",
    "Arabic Egypt":"ar-EG",
    "Arabic Israel":"ar-IL",
    "Arabic Iraq":"ar-IQ",
    "Arabic Jordan":"ar-JO",
    "Arabic Kuwait":"ar-KW",
    "Arabic Lebanon":"ar-LB",
    "Arabic Morocco":"ar-MA",
    "Arabic Oman":"ar-OM",
    "Arabic Palestinian Territory":"ar-PS",
    "Arabic Qatar":"ar-QA",
    "Arabic Saudi Arabia":"ar-SA",
    "Arabic Tunisia":"ar-TN",
    "Arabic UAE":"ar-AE",
    "Euskara Spain":"eu-ES",
    "Bulgarian Bulgaria":"bg-BG",
    "Catalan Spain":"ca-ES",
    "Mongolian China (Simp.)":"cmn-Hans-CN",
    "Mongolian Hong Kong SAR (Trad.)":"cmn-Hans-HK",
    "Mongolian Taiwan (Trad.)":"cmn-Hant-TW",
    "Cantonese Hong Kong":"yue-Hant-HK",
    "Hrvatska Croatia":"hr_HR",
    "Czech Republic":"cs-CZ",
    "Danish Denmark":"da-DK",
    "English Australia":"en-AU",
    "English Canada":"en-CA",
    "English India":"en-IN",
    "English Ireland":"en-IE",
    "English New Zealand":"en-NZ",
    "English Philippines":"en-PH",
    "English South Africa":"en-ZA",
    "Persian Iran":"fa-IR",
    "French France":"fr-FR",
    "Filipino Philippines":"fil-PH",
    "Galician Spain":"gl-ES",
    "German Germany":"de-DE",
    "Greek Greece":"el-GR",
    "Finnish Finland":"fi-FI",
    "Hebrew Israel":"he-IL",
    "Hindi India":"hi-IN",
    "Hungarian Hungary":"hu-HU",
    "Indonesian Indonesia":"id-ID",
    "Icelandic Iceland":"is-IS",
    "Italian Italy":"it-IT",
    "Italian Switzerland":"it-CH",
    "Korean Korea":"ko-KR",
    "Lithuanian Lithuania":"lt-LT",
    "Malay Malaysia":"ms-MY",
    "Nederlands Netherlands":"nl-NL",
    "Bokmål Norway":"nb-NO",
    "Polski Poland":"pl-PL",
    "Português Brazil":"pt-BR",
    "Português Portugal":"pt-PT",
    "limba română Romania":"ro-RO",
    "Russian Russia":"ru-RU",
    "Serbian Serbia":"sr-RS",
    "Slovak Slovakia":"sk-SK",
    "Slovenian Slovenia":"sl-SI",
    "Spanish Argentina":"es-AR",
    "Spanish Bolivia":"es-BO",
    "Spanish Chile":"es-CL",
    "Spanish Colombia":"es-CO",
    "Spanish Costa Rica":"es-CR",
    "Spanish Dominican Republic":"es-DO",
    "Spanish Ecuador":"es-EC",
    "Spanish El Salvador":"es-SV",
    "Spanish Guatemala":"es-GT",
    "Spanish Honduras":"es-HN",
    "Spanish México":"es-MX",
    "Spanish Nicaragua":"es-NI",
    "Spanish Panamá":"es-PA",
    "Spanish Paraguay":"es-PY",
    "Spanish Perú":"es-PE",
    "Spanish Puerto Rico":"es-PR",
    "Spanish Spain":"es-ES",
    "Spanish Uruguay":"es-UY",
    "Spanish United States":"es-US",
    "Spanish Venezuela":"es-VE",
    "Swedish Sweden":"sv-SE",
    "Thai Thailand":"th-TH",
    "Turkish Turkey":"tr-TR",
    "Ukrainian Ukraine":"uk-UA",
    "Vietnamese Viet Nam":"vi-VN",
    "Zulu South Africa":"zu-ZA"
}

translators = ["DeepL(web)", "DeepL(auth)", "Google(web)", "Bing(web)"]
translation_lang = {}
translation_lang["DeepL(web)"] = {
    "Japanese":"JA",
    "English":"EN",
    "Bulgarian":"BG",
    "Chinese":"ZH",
    "Czech":"CS",
    "Danish":"DA",
    "Dutch":"NL",
    "Estonian":"ET",
    "Finnish":"FI",
    "French":"FR",
    "German":"DE",
    "Greek":"EL",
    "Hungarian":"HU",
    "Italian":"IT",
    "Latvian":"LV",
    "Lithuanian":"LT",
    "Polish":"PL",
    "Portuguese":"PT",
    "Romanian":"RO",
    "Russian":"RU",
    "Slovak":"SK",
    "Slovenian":"SL",
    "Spanish":"ES",
    "Swedish":"SV"
}
translation_lang["DeepL(auth)"] = {
    "Japanese":"ja",
    "English American":"en-US",
    "English British":"en-GB",
    "Bulgarian":"bg",
    "Czech":"cs",
    "Danish":"da",
    "German":"de",
    "Greek":"el",
    "English":"en",
    "Spanish":"es",
    "Estonian":"et",
    "Finnish":"fi",
    "French":"fr",
    "Hungarian":"hu",
    "Indonesian":"id",
    "Italian":"it",
    "Korean":"ko",
    "Lithuanian":"lt",
    "Latvian":"lv",
    "Norwegian":"nb",
    "Dutch":"nl",
    "Polish":"pl",
    "Portuguese":"pt",
    "Portuguese Brazilian":"pt-BR",
    "Portuguese European":"pt-PT",
    "Romanian":"ro",
    "Russian":"ru",
    "Slovak":"sk",
    "Slovenian":"sl",
    "Swedish":"sv",
    "Turkish":"tr",
    "Ukrainian":"uk",
    "Chinese":"zh"
}
translation_lang["Google(web)"] = {
    "Japanese":"ja",
    "English":"en",
    "Chinese":"zh",
    "Arabic":"ar",
    "Russian":"ru",
    "French":"fr",
    "German":"de",
    "Spanish":"es",
    "Portuguese":"pt",
    "Italian":"it",
    "Korean":"ko",
    "Greek":"el",
    "Dutch":"nl",
    "Hindi":"hi",
    "Turkish":"tr",
    "Malay":"ms",
    "Thai":"th",
    "Vietnamese":"vi",
    "Indonesian":"id",
    "Hebrew":"he",
    "Polish":"pl",
    "Mongolian":"mn",
    "Czech":"cs",
    "Hungarian":"hu",
    "Estonian":"et",
    "Bulgarian":"bg",
    "Danish":"da",
    "Finnish":"fi",
    "Romanian":"ro",
    "Swedish":"sv",
    "Slovenian":"sl",
    "Persian/Farsi":"fa",
    "Bosnian":"bs",
    "Serbian":"sr",
    "Filipino":"tl",
    "Haitiancreole":"ht",
    "Catalan":"ca",
    "Croatian":"hr",
    "Latvian":"lv",
    "Lithuanian":"lt",
    "Urdu":"ur",
    "Ukrainian":"uk",
    "Welsh":"cy",
    "Swahili":"sw",
    "Samoan":"sm",
    "Slovak":"sk",
    "Afrikaans":"af",
    "Norwegian":"no",
    "Bengali":"bn",
    "Malagasy":"mg",
    "Maltese":"mt",
    "Gujarati":"gu",
    "Tamil":"ta",
    "Telugu":"te",
    "Punjabi":"pa",
    "Amharic":"am",
    "Azerbaijani":"az",
    "Belarusian":"be",
    "Cebuano":"ceb",
    "Esperanto":"eo",
    "Basque":"eu",
    "Irish":"ga"
}
translation_lang["Bing(web)"] = {
    "Japanese":"ja",
    "English":"en",
    "Chinese":"zh",
    "Arabic":"ar",
    "Russian":"ru",
    "French":"fr",
    "German":"de",
    "Spanish":"es",
    "Portuguese":"pt",
    "Italian":"it",
    "Korean":"ko",
    "Greek":"el",
    "Dutch":"nl",
    "Hindi":"hi",
    "Turkish":"tr",
    "Malay":"ms",
    "Thai":"th",
    "Vietnamese":"vi",
    "Indonesian":"id",
    "Hebrew":"he",
    "Polish":"pl",
    "Czech":"cs",
    "Hungarian":"hu",
    "Estonian":"et",
    "Bulgarian":"bg",
    "Danish":"da",
    "Finnish":"fi",
    "Romanian":"ro",
    "Swedish":"sv",
    "Slovenian":"sl",
    "Persian/Farsi":"fa",
    "Bosnian":"bs",
    "Serbian":"sr",
    "Fijian":"fj",
    "Filipino":"tl",
    "Haitiancreole":"ht",
    "Catalan":"ca",
    "Croatian":"hr",
    "Latvian":"lv",
    "Lithuanian":"lt",
    "Urdu":"ur",
    "Ukrainian":"uk",
    "Welsh":"cy",
    "Tahiti":"ty",
    "Tongan":"to",
    "Swahili":"sw",
    "Samoan":"sm",
    "Slovak":"sk",
    "Afrikaans":"af",
    "Norwegian":"no",
    "Bengali":"bn",
    "Malagasy":"mg",
    "Maltese":"mt",
    "Queretaro otomi":"otq",
    "Klingon/tlhingan Hol":"tlh",
    "Gujarati":"gu",
    "Tamil":"ta",
    "Telugu":"te",
    "Punjabi":"pa",
    "Irish":"ga"
}

selectable_languages = {
    "en": "English",
    "ja": "日本語",
    "ko": "한국어"
    # 新しい言語とキーを追加する場合はここに追記してください
}