recognize_lang = {
    "Japanese Japan":"ja-JP",
    "English United States":"en-US",
    "English United Kingdom":"en-GB",
    "Afrikaans South Africa":"af-ZA",
    "Arabic Algeria":"ar-DZ",
    "Arabic Bahrain":"ar-BH",
    "Arabic Egypt":"ar-EG",
    "Arabic Israel":"ar-IL",
    "Arabic Iraq":"ar-IQ",
    "Arabic Jordan":"ar-JO",
    "Arabic Kuwait":"ar-KW",
    "Arabic Lebanon":"ar-LB",
    "Arabic Morocco":"ar-MA",
    "Arabic Oman":"ar-OM",
    "Arabic Palestinian Territory":"ar-PS",
    "Arabic Qatar":"ar-QA",
    "Arabic Saudi Arabia":"ar-SA",
    "Arabic Tunisia":"ar-TN",
    "Arabic UAE":"ar-AE",
    "Euskara Spain":"eu-ES",
    "Bulgarian Bulgaria":"bg-BG",
    "Catalan Spain":"ca-ES",
    "Mongolian China (Simp.)":"cmn-Hans-CN",
    "Mongolian Hong Kong SAR (Trad.)":"cmn-Hans-HK",
    "Mongolian Taiwan (Trad.)":"cmn-Hant-TW",
    "Cantonese Hong Kong":"yue-Hant-HK",
    "Hrvatska Croatia":"hr_HR",
    "Czech Republic":"cs-CZ",
    "Danish Denmark":"da-DK",
    "English Australia":"en-AU",
    "English Canada":"en-CA",
    "English India":"en-IN",
    "English Ireland":"en-IE",
    "English New Zealand":"en-NZ",
    "English Philippines":"en-PH",
    "English South Africa":"en-ZA",
    "Persian Iran":"fa-IR",
    "French France":"fr-FR",
    "Filipino Philippines":"fil-PH",
    "Galician Spain":"gl-ES",
    "German Germany":"de-DE",
    "Greek Greece":"el-GR",
    "Finnish Finland":"fi-FI",
    "Hebrew Israel":"he-IL",
    "Hindi India":"hi-IN",
    "Hungarian Hungary":"hu-HU",
    "Indonesian Indonesia":"id-ID",
    "Icelandic Iceland":"is-IS",
    "Italian Italy":"it-IT",
    "Italian Switzerland":"it-CH",
    "Korean Korea":"ko-KR",
    "Lithuanian Lithuania":"lt-LT",
    "Malay Malaysia":"ms-MY",
    "Nederlands Netherlands":"nl-NL",
    "Bokmål Norway":"nb-NO",
    "Polski Poland":"pl-PL",
    "Português Brazil":"pt-BR",
    "Português Portugal":"pt-PT",
    "limba română Romania":"ro-RO",
    "Russian Russia":"ru-RU",
    "Serbian Serbia":"sr-RS",
    "Slovak Slovakia":"sk-SK",
    "Slovenian Slovenia":"sl-SI",
    "Spanish Argentina":"es-AR",
    "Spanish Bolivia":"es-BO",
    "Spanish Chile":"es-CL",
    "Spanish Colombia":"es-CO",
    "Spanish Costa Rica":"es-CR",
    "Spanish Dominican Republic":"es-DO",
    "Spanish Ecuador":"es-EC",
    "Spanish El Salvador":"es-SV",
    "Spanish Guatemala":"es-GT",
    "Spanish Honduras":"es-HN",
    "Spanish México":"es-MX",
    "Spanish Nicaragua":"es-NI",
    "Spanish Panamá":"es-PA",
    "Spanish Paraguay":"es-PY",
    "Spanish Perú":"es-PE",
    "Spanish Puerto Rico":"es-PR",
    "Spanish Spain":"es-ES",
    "Spanish Uruguay":"es-UY",
    "Spanish United States":"es-US",
    "Spanish Venezuela":"es-VE",
    "Swedish Sweden":"sv-SE",
    "Thai Thailand":"th-TH",
    "Turkish Turkey":"tr-TR",
    "Ukrainian Ukraine":"uk-UA",
    "Vietnamese Viet Nam":"vi-VN",
    "Zulu South Africa":"zu-ZA"
}

deepl_lang = {
    "Japanese":"ja",
    "English American":"en-US",
    "English British":"en-GB",
    "Bulgarian":"bg",
    "Czech":"cs",
    "Danish":"da",
    "German":"de",
    "Greek":"el",
    "English":"en",
    "Spanish":"es",
    "Estonian":"et",
    "Finnish":"fi",
    "French":"fr",
    "Hungarian":"hu",
    "Indonesian":"id",
    "Italian":"it",
    "Korean":"ko",
    "Lithuanian":"lt",
    "Latvian":"lv",
    "Norwegian":"nb",
    "Dutch":"nl",
    "Polish":"pl",
    "Portuguese":"pt",
    "Portuguese Brazilian":"pt-BR",
    "Portuguese European":"pt-PT",
    "Romanian":"ro",
    "Russian":"ru",
    "Slovak":"sk",
    "Slovenian":"sl",
    "Swedish":"sv",
    "Turkish":"tr",
    "Ukrainian":"uk",
    "Chinese":"zh"
}

deepl_translate_lang = {
    "Japanese":"JA",
    "English":"EN",
    "Bulgarian":"BG",
    "Chinese":"ZH",
    "Czech":"CS",
    "Danish":"DA",
    "Dutch":"NL",
    "Estonian":"ET",
    "Finnish":"FI",
    "French":"FR",
    "German":"DE",
    "Greek":"EL",
    "Hungarian":"HU",
    "Italian":"IT",
    "Latvian":"LV",
    "Lithuanian":"LT",
    "Polish":"PL",
    "Portuguese":"PT",
    "Romanian":"RO",
    "Russian":"RU",
    "Slovak":"SK",
    "Slovenian":"SL",
    "Spanish":"ES",
    "Swedish":"SV"
}

translators_bing_lang = {
    "japanese":"ja",
    "english":"en",
    "chinese":"zh",
    "arabic":"ar",
    "russian":"ru",
    "french":"fr",
    "german":"de",
    "spanish":"es",
    "portuguese":"pt",
    "italian":"it",
    "korean":"ko",
    "greek":"el",
    "dutch":"nl",
    "hindi":"hi",
    "turkish":"tr",
    "malay":"ms",
    "thai":"th",
    "vietnamese":"vi",
    "indonesian":"id",
    "hebrew":"he",
    "polish":"pl",
    "czech":"cs",
    "hungarian":"hu",
    "estonian":"et",
    "bulgarian":"bg",
    "danish":"da",
    "finnish":"fi",
    "romanian":"ro",
    "swedish":"sv",
    "slovenian":"sl",
    "persian/farsi":"fa",
    "bosnian":"bs",
    "serbian":"sr",
    "fijian":"fj",
    "filipino":"tl",
    "haitiancreole":"ht",
    "catalan":"ca",
    "croatian":"hr",
    "latvian":"lv",
    "lithuanian":"lt",
    "urdu":"ur",
    "ukrainian":"uk",
    "welsh":"cy",
    "tahiti":"ty",
    "tongan":"to",
    "swahili":"sw",
    "samoan":"sm",
    "slovak":"sk",
    "afrikaans":"af",
    "norwegian":"no",
    "bengali":"bn",
    "malagasy":"mg",
    "maltese":"mt",
    "queretaro otomi":"otq",
    "klingon/tlhingan hol":"tlh",
    "gujarati":"gu",
    "tamil":"ta",
    "telugu":"te",
    "punjabi":"pa",
    "irish":"ga"
}

translators_google_lang = {
    "japanese":"ja",
    "english":"en",
    "chinese":"zh",
    "arabic":"ar",
    "russian":"ru",
    "french":"fr",
    "german":"de",
    "spanish":"es",
    "portuguese":"pt",
    "italian":"it",
    "korean":"ko",
    "greek":"el",
    "dutch":"nl",
    "hindi":"hi",
    "turkish":"tr",
    "malay":"ms",
    "thai":"th",
    "vietnamese":"vi",
    "indonesian":"id",
    "hebrew":"he",
    "polish":"pl",
    "mongolian":"mn",
    "czech":"cs",
    "hungarian":"hu",
    "estonian":"et",
    "bulgarian":"bg",
    "danish":"da",
    "finnish":"fi",
    "romanian":"ro",
    "swedish":"sv",
    "slovenian":"sl",
    "persian/farsi":"fa",
    "bosnian":"bs",
    "serbian":"sr",
    "filipino":"tl",
    "haitiancreole":"ht",
    "catalan":"ca",
    "croatian":"hr",
    "latvian":"lv",
    "lithuanian":"lt",
    "urdu":"ur",
    "ukrainian":"uk",
    "welsh":"cy",
    "swahili":"sw",
    "samoan":"sm",
    "slovak":"sk",
    "afrikaans":"af",
    "norwegian":"no",
    "bengali":"bn",
    "malagasy":"mg",
    "maltese":"mt",
    "gujarati":"gu",
    "tamil":"ta",
    "telugu":"te",
    "punjabi":"pa",
    "amharic":"am",
    "azerbaijani":"az",
    "belarusian":"be",
    "cebuano":"ceb",
    "esperanto":"eo",
    "basque":"eu",
    "irish":"ga"
}