from types import SimpleNamespace

from .Themes import _darkTheme, _lightTheme

class ColorThemeManager():
    def __init__(self, theme):
        # base_color 100, 200, 300...900 is generated by https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors . I put the comment "Source". I used it as a source color and generated.
        # and like 750, 888... is made by https://meyerweb.com/eric/tools/color-blend/#:::hex

        self.base_color = SimpleNamespace(

            PRIMARY_100_COLOR = "#b7ded8",
            PRIMARY_150_COLOR = "#A1D4CC",
            PRIMARY_200_COLOR = "#8acac0",
            PRIMARY_250_COLOR = "#76BFB4",
            PRIMARY_300_COLOR = "#61b4a7",
            PRIMARY_350_COLOR = "#55AC9E",
            PRIMARY_400_COLOR = "#48a495", # Source
            PRIMARY_450_COLOR = "#429c8c",
            PRIMARY_500_COLOR = "#3b9483",
            PRIMARY_600_COLOR = "#368777",
            PRIMARY_650_COLOR = "#347f6f",
            PRIMARY_700_COLOR = "#317767",
            PRIMARY_750_COLOR = "#2F6F60",
            PRIMARY_800_COLOR = "#2c6759",
            PRIMARY_900_COLOR = "#214b3f",

            SENT_400_COLOR = "#6197b4", # Source PRIMARY_300_COLOR #61b4a7. ANALOGOUS' Second one.
            RECEIVED_300_COLOR = "#a861b4", # Source PRIMARY_300_COLOR #61b4a7. TRIADIC' Second one.

            DARK_BASIC_TEXT_COLOR = "#f2f2f2", # Icon normal color too
            DARK_100_COLOR = "#f5f7fb", # THE LIGHTEST BG COLOR
            DARK_200_COLOR = "#f1f2f6",
            DARK_300_COLOR = "#e9eaee",
            DARK_350_COLOR = "#d8d9dd",
            DARK_400_COLOR = "#c7c8cc", # Icon second color
            DARK_450_COLOR = "#b8b9bd",
            DARK_500_COLOR = "#a9aaae",
            DARK_600_COLOR = "#7f8084",
            DARK_650_COLOR = "#75767a",
            DARK_700_COLOR = "#6a6c6f",
            DARK_725_COLOR = "#636467",
            DARK_750_COLOR = "#5b5c5f",
            DARK_775_COLOR = "#535457",
            DARK_800_COLOR = "#4b4c4f",
            DARK_825_COLOR = "#434447",
            DARK_850_COLOR = "#3a3b3e",
            DARK_863_COLOR = "#36373a",
            DARK_875_COLOR = "#323336",
            DARK_888_COLOR = "#2e2f32",
            DARK_900_COLOR = "#292a2d", # Source
            DARK_925_COLOR = "#242528",
            DARK_950_COLOR = "#1f2022",
            DARK_975_COLOR = "#1a1b1d",
            DARK_1000_COLOR = "#151517", # THE DARKEST BG COLOR


            LIGHT_BASIC_TEXT_COLOR = "#050505",
            LIGHT_100_COLOR = "#f5f7fb", # THE LIGHTEST BG COLOR
            LIGHT_125_COLOR = "#F4F6FA",
            LIGHT_150_COLOR = "#F2F4F8",
            LIGHT_175_COLOR = "#F1F3F7",
            LIGHT_200_COLOR = "#eff1f5",
            LIGHT_225_COLOR = "#ECEEF2",
            LIGHT_250_COLOR = "#E9EBEF",
            LIGHT_275_COLOR = "#E6E8EC",
            LIGHT_300_COLOR = "#e2e4e8",
            LIGHT_313_COLOR = "#DEE0E4",
            LIGHT_325_COLOR = "#DADCE0",
            LIGHT_333_COLOR = "#D6D8DC",
            LIGHT_350_COLOR = "#D1D3D7",
            LIGHT_375_COLOR = "#C9CBCF",
            LIGHT_400_COLOR = "#c0c2c6",
            LIGHT_450_COLOR = "#B1B3B7",
            LIGHT_500_COLOR = "#a2a3a7",
            LIGHT_550_COLOR = "#8D8F93",
            LIGHT_600_COLOR = "#787a7e",
            LIGHT_700_COLOR = "#646669", # Icon second color
            LIGHT_800_COLOR = "#45464a",
            LIGHT_900_COLOR = "#242528", # Icon normal color
            LIGHT_1000_COLOR = "#1b1b1b", # THE DARKEST BG COLOR
        )


        # It's actually meaningless to separate it from __init__. but it's just set to use the dark theme by default, so I did it just in case to change the default theme.
        selected_color_theme = _darkTheme(self.base_color)
        for each_key in selected_color_theme.__dict__.keys():
            setattr(self, each_key, getattr(selected_color_theme, each_key))


        if theme == "Dark":
            pass

        elif theme == "Light":
            selected_color_theme = _lightTheme(self.base_color)
            self._colorThemeDictsMerger(selected_color_theme)





    def _colorThemeDictsMerger(self, selected_color_theme):
        # Each section(main, selectable_language_window, config_window...) marge to default theme.
        for selected_theme_section_key in selected_color_theme.__dict__.keys():
            # Get same section data by section key from default theme.
            default_theme_target_section_data = getattr(self, selected_theme_section_key)

            selected_theme_section_data = getattr(selected_color_theme, selected_theme_section_key)
            self._mergeNestedDicts(default_theme_target_section_data.__dict__, selected_theme_section_data.__dict__)



    def _mergeNestedDicts(self, d1, d2):
        for key, value in d2.items():
            if key in d1 and isinstance(d1[key], dict) and isinstance(value, dict):
                self._mergeNestedDicts(d1[key], value)
            else:
                d1[key] = value

        return d1
