transcription_lang = {
    "Japanese (Japan)":"ja-JP",
    "English (United States)":"en-US",
    "English (United Kingdom)":"en-GB",
    "Afrikaans (South Africa)":"af-ZA",
    "Arabic (Algeria)":"ar-DZ",
    "Arabic (Bahrain)":"ar-BH",
    "Arabic (Egypt)":"ar-EG",
    "Arabic (Israel)":"ar-IL",
    "Arabic (Iraq)":"ar-IQ",
    "Arabic (Jordan)":"ar-JO",
    "Arabic (Kuwait)":"ar-KW",
    "Arabic (Lebanon)":"ar-LB",
    "Arabic (Morocco)":"ar-MA",
    "Arabic (Oman)":"ar-OM",
    "Arabic (State of Palestine)":"ar-PS",
    "Arabic (Qatar)":"ar-QA",
    "Arabic (Saudi Arabia)":"ar-SA",
    "Arabic (Tunisia)":"ar-TN",
    "Arabic (United Arab Emirates)":"ar-AE",
    "Basque (Spain)":"eu-ES",
    "Bulgarian (Bulgaria)":"bg-BG",
    "Catalan (Spain)":"ca-ES",
    "Chinese, Mandarin (Simplified, China)":"cmn-Hans-CN",
    "Chinese, Mandarin (Simplified, Hong Kong)":"cmn-Hans-HK",
    "Chinese, Mandarin (Traditional, Taiwan)":"cmn-Hant-TW",
    "Chinese, Cantonese (Traditional Hong Kong)":"yue-Hant-HK",
    "Croatian (Croatia)":"hr-HR",
    "Czech (Czech Republic)":"cs-CZ",
    "Danish (Denmark)":"da-DK",
    "English (Australia)":"en-AU",
    "English (Canada)":"en-CA",
    "English (India)":"en-IN",
    "English (Ireland)":"en-IE",
    "English (New Zealand)":"en-NZ",
    "English (Philippines)":"en-PH",
    "English (South Africa)":"en-ZA",
    "Persian (Iran)":"fa-IR",
    "French (France)":"fr-FR",
    "Filipino (Philippines)":"fil-PH",
    "Galician (Spain)":"gl-ES",
    "German (Germany)":"de-DE",
    "Greek (Greece)":"el-GR",
    "Finnish (Finland)":"fi-FI",
    "Hebrew (Israel)":"he-IL",
    "Hindi (India)":"hi-IN",
    "Hungarian (Hungary)":"hu-HU",
    "Indonesian (Indonesia)":"id-ID",
    "Icelandic (Iceland)":"is-IS",
    "Italian (Italy)":"it-IT",
    "Italian (Switzerland)":"it-CH",
    "Korean (South Korea)":"ko-KR",
    "Lithuanian (Lithuania)":"lt-LT",
    "Malay (Malaysia)":"ms-MY",
    "Dutch (Netherlands)":"nl-NL",
    "Norwegian Bokmål (Norway)":"nb-NO",
    "Polish (Poland)":"pl-PL",
    "Portuguese (Brazil)":"pt-BR",
    "Portuguese (Portugal)":"pt-PT",
    "Romanian (Romania)":"ro-RO",
    "Russian (Russia)":"ru-RU",
    "Serbian (Serbia)":"sr-RS",
    "Slovak (Slovakia)":"sk-SK",
    "Slovenian (Slovenia)":"sl-SI",
    "Spanish (Argentina)":"es-AR",
    "Spanish (Bolivia)":"es-BO",
    "Spanish (Chile)":"es-CL",
    "Spanish (Colombia)":"es-CO",
    "Spanish (Costa Rica)":"es-CR",
    "Spanish (Dominican Republic)":"es-DO",
    "Spanish (Ecuador)":"es-EC",
    "Spanish (El Salvador)":"es-SV",
    "Spanish (Guatemala)":"es-GT",
    "Spanish (Honduras)":"es-HN",
    "Spanish (Mexico)":"es-MX",
    "Spanish (Nicaragua)":"es-NI",
    "Spanish (Panama)":"es-PA",
    "Spanish (Paraguay)":"es-PY",
    "Spanish (Peru)":"es-PE",
    "Spanish (Puerto Rico)":"es-PR",
    "Spanish (Spain)":"es-ES",
    "Spanish (Uruguay)":"es-UY",
    "Spanish (United States)":"es-US",
    "Spanish (Venezuela)":"es-VE",
    "Swedish (Sweden)":"sv-SE",
    "Thai (Thailand)":"th-TH",
    "Turkish (Turkey)":"tr-TR",
    "Ukrainian (Ukraine)":"uk-UA",
    "Vietnamese (Vietnam)":"vi-VN",
    "Zulu (South Africa)":"zu-ZA"
}